arrowParens: always
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
htmlWhitespaceSensitivity: css
jsxSingleQuote: true
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
